### ISSUE TITLE
批量报错

### ISSUE THREAD

**Issue by xiaojinbing** [914525753/AutoDomain#2]
![image](https://user-images.githubusercontent.com/66505644/233853782-f61d50df-b440-4aa4-981e-a68e024c42b4.png)

**Comment by shadowabi** [comment]
python3.10不兼容本程序，可以先用python3.10以下的版本，比如python3.8
稍后我会排查具体是什么原因导致的不兼容

**Comment by shadowabi** [comment]
python3.10不兼容本程序，可以先用python3.10以下的版本，比如python3.8
稍后我排除具体是什么原因导致的不兼容

**Comment by shadowabi** [comment]
我已经把全部代码重构为go语言了，现在不会报错了
