### ISSUE TITLE
资产数量问题

### ISSUE THREAD

**Issue by guanglianniubi** [914525753/AutoDomain#4]
模式为all的时候会漏掉某些资产，单独选quake资产又可以识别出漏掉的，是做了什么过滤吗

**Comment by shadowabi** [comment]
可能是网络请求波动，也可能是多线程引发的条件竞争问题，已经加上互斥锁进行缓解了，我这边暂时没有太好的解决方案

**Comment by shadowabi** [comment]
已对代码进行重构，你可以试试最新版是否还会出现这个问题

**Comment by guanglianniubi** [comment]
不支持检索ip=“xxx”吗

**Comment by guanglianniubi** [comment]
文件列表里放一个ip去获取，还是会漏，看了下你的检索语法只能是domain="xxx"?

**Comment by guanglianniubi** [comment]
还是会漏，不太清除是为什么
