### ISSUE TITLE
希望可以针对自定义搜索引擎

### ISSUE THREAD

**Issue by RuoJi6** [914525753/AutoDomain#5]
师傅能否添加一个参数，就是可以自定义传入一些参数，进行搜索
1、导出json格式数据
2、查询得到网站之后，根据网站的SSL证书进行二次查询，去重

**Comment by shadowabi** [comment]
已实现，具体可见 [Release 2.11](https://github.com/shadowabi/AutoDomain/releases/tag/2.11) ，代码详情见 [commit](https://github.com/shadowabi/AutoDomain/commit/8a037299a9f7a9f6a9799f1969cb38fdb3f5965c)
